---
blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/CleatSquad/magento-frankenphp-images/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/CleatSquad/magento-frankenphp-images/discussions
    about: Ask questions and share ideas in GitHub Discussions
